标量由只有一个元素的张量表示

In [2]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [4]:
x = torch.arange(4)
x[3]

tensor(3)

In [12]:
len(x)

4

In [13]:
x.shape

torch.Size([4])

In [14]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

矩阵的转置

In [15]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [18]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [19]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone() #通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [21]:
x = torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [22]:
A = torch.arange(40).reshape(2,5,4)
A.shape,A.sum()

(torch.Size([2, 5, 4]), tensor(780))

指定求和汇总张量的轴

In [ ]:
A_sum_axis0 = A.sum(axis=0) #在第一个维度进行求和
A,A_sum_axis0, A_sum_axis0.shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]),
 tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [25]:
A_sum_axis1 = A.sum(axis=1) #在第二个维度进行求和
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

In [27]:
A.sum(axis=[0,1]) #在第一个和第二个维度进行求和

tensor([180, 190, 200, 210])

In [33]:
A.mean(dtype=torch.float32), A.sum()/A.numel()

(tensor(19.5000), tensor(19.5000))

按某个维度求和时不把它丢掉(可以用于广播机制，保持维度一致)

In [35]:
sum_A = A.sum(axis=1,keepdim=True) #在第二个维度进行求和，并保持维度不变
sum_A, sum_A.shape

(tensor([[[ 40,  45,  50,  55]],
 
         [[140, 145, 150, 155]]]),
 torch.Size([2, 1, 4]))

In [38]:
A/sum_A

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

某个轴计算A元素的累计总和

In [41]:
A=torch.arange(20).reshape(5,4)
A,A.cumsum(axis=0) #在第一个维度上累积求和

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  6,  8, 10],
         [12, 15, 18, 21],
         [24, 28, 32, 36],
         [40, 45, 50, 55]]))

矩阵向量积

In [47]:
x = torch.arange(4)
A.shape, x.shape, torch.mv(A,x) #矩阵-向量积

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14,  38,  62,  86, 110]))

矩阵乘法

In [49]:
B = torch.ones(4,3)
torch.mm(A.float(),B) 

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

L2范数

In [50]:
u = torch.tensor([3.0,-4.0])
torch.norm(u) 

tensor(5.)

L1范数

In [51]:
torch.abs(u).sum()

tensor(7.)

F范数：**矩阵**元素的平方和的平方根

In [52]:
torch.norm(torch.ones((4,9)))

tensor(6.)